//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drama
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Drama()
        {
            this.Actors = new HashSet<Actor>();
        }
    
        public int DramaID { get; set; }
        public int DirectorID { get; set; }
        public int SWID { get; set; }
        public int DramaTypeID { get; set; }
        public string Title { get; set; }
        public int ReleaseYear { get; set; }
    
        public virtual Director Director { get; set; }
        public virtual DramaType DramaType { get; set; }
        public virtual ScriptWriter ScriptWriter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Actor> Actors { get; set; }
    }
}
