//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DramaDetail
    {
        public string Director_Name { get; set; }
        public string Writer_Name { get; set; }
        public string Actor_ActressName { get; set; }
        public string Drama_Name { get; set; }
        public int Release_Year { get; set; }
    }
}
