//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DramaManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDramaList
    {
        public int DramaID { get; set; }
        public string Title { get; set; }
        public int ReleaseYear { get; set; }
        public string ScriptWriter { get; set; }
        public string TypeName { get; set; }
        public string Directors { get; set; }
    }
}
